import React, { useState } from 'react';
import { useQueue } from '../../state/QueueContext';
import { formatCurrency, maskCustomerId, formatDateTime } from '../../utils/formatters';
import { ReceiptPreviewModal } from '../../components/receipt/ReceiptPreviewModal';
import { Printer, Eye, Receipt } from 'lucide-react';

export const ReceiptsPage = () => {
  const { queueList } = useQueue();
  const [selectedReceipt, setSelectedReceipt] = useState(null);

  const liveReceipts = queueList
    .filter((q) => q.ui_status === 'COMPLETED')
    .map((q, idx) => ({
      receipt_id: `RCP-2026-${9902 + idx}`,
      token_id: q.token_id,
      customer_display_name: q.customer_display_name,
      transaction_type: q.transaction_type,
      amount: q.amount,
      issued_at: q.completed_at || q.issued_at,
      staff_id: 'STAFF-042'
    }));

  const allReceipts = liveReceipts;

  return (
    <div className="card">
      <div className="card-title">
        Issued Receipts Archive
      </div>
      <div className="card-subtitle">
        Historical audit of transaction receipts generated by Terminal ST-042.
      </div>

      <div className="table-container">
        <table className="banking-table">
          <thead>
            <tr>
              <th>Receipt ID</th>
              <th>Transaction ID</th>
              <th>Customer</th>
              <th>Service</th>
              <th>Amount</th>
              <th>Staff</th>
              <th>Issued At</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {allReceipts.length === 0 ? (
              <tr>
                <td colSpan={8} style={{ textAlign: 'center', padding: '2.5rem', color: '#64748B' }}>
                  No receipts issued yet. Receipts are generated upon transaction completion.
                </td>
              </tr>
            ) : (
              allReceipts.map((rcp) => (
                <tr key={rcp.receipt_id}>
                  <td style={{ fontWeight: 700, color: '#12355B' }}>
                    {rcp.receipt_id}
                  </td>
                  <td style={{ fontFamily: 'monospace' }}>
                    {rcp.token_id}
                  </td>
                  <td style={{ fontWeight: 600 }}>
                    {maskCustomerId(rcp.customer_display_name)}
                  </td>
                  <td style={{ textTransform: 'capitalize' }}>
                    {rcp.transaction_type}
                  </td>
                  <td style={{ fontWeight: 600 }}>
                    {formatCurrency(rcp.amount)}
                  </td>
                  <td>{rcp.staff_id}</td>
                  <td style={{ fontSize: '0.82rem', color: '#64748B' }}>
                    {formatDateTime(rcp.issued_at)}
                  </td>
                  <td>
                    <div className="flex gap-2">
                      <button 
                        className="btn btn-secondary" 
                        style={{ padding: '0.3rem 0.55rem', fontSize: '0.75rem' }}
                        onClick={() => setSelectedReceipt(rcp)}
                      >
                        <Eye size={13} />
                        <span>View</span>
                      </button>
                      <button 
                        className="btn btn-primary" 
                        style={{ padding: '0.3rem 0.55rem', fontSize: '0.75rem' }}
                        onClick={() => setSelectedReceipt(rcp)}
                      >
                        <Printer size={13} />
                        <span>Print</span>
                      </button>
                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      <ReceiptPreviewModal 
        isOpen={Boolean(selectedReceipt)}
        receiptData={selectedReceipt}
        onClose={() => setSelectedReceipt(null)}
      />
    </div>
  );
};
